version: "3"
services:
  mysql-standalone:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=feres
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
  timesheet:
    image: feresmch/timesheet:55
    ports:
      - 8086:8086
    restart: unless-stopped
    depends_on:
      - mysql-standalone