version: "3"
services:
  mysql-standalone:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=radhouan
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    ports:
      - 3306:3306
  reclamation:
    image: reclamation:latest
    ports:
      - 8055:8055
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone