version: "3"
services:
  mysql-standalone:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ala
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
  timesheet:
    image: department:latest
    ports:
      - 8085:8085
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone